version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt

  build_docker_image:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true # enable Docker layer caching for faster builds
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Build and Push Docker Image to AWS ECR
          command: |
            TAG=0.1$CIRCLE_BUILD_NUM
            ECR_URI="$AWS_ECR_REGISTRY_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
            IMAGE_URI="$ECR_URI/django_circleci:$TAG"

            # Authenticate Docker to AWS ECR
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI

            # Build the Docker image
            docker build -t django_circleci -t $IMAGE_URI .

            # Push the Docker image to AWS ECR
            docker push $IMAGE_URI

workflows:
  build_and_deploy:
    jobs:
      - build
      - build_docker_image:
          requires:
            - build
          filters:
            branches:
              only: main
