version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2024.06
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}
    steps:
        - checkout
        - run:
            name: Build_Image
            command: |
              TAG=0.1$CIRCLE_BUILD_NUM
              docker build -t $DOCKERHUB_USERNAME/djangotask:$TAG .
  deploy:
    docker:
    - image: cimg/base:2024.06
    steps:
      - checkout
      - run: 
          name: Pushing the Image to Docker_Hub
          command: |
              TAG=0.1$CIRCLE_BUILD_NUM
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker push $DOCKER_USERNAME/djangotask:$TAG

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main